### ISSUE TITLE
CUDNN_STATUS_BAD_PARAM in NStepLSTM

### ISSUE THREAD

**Issue by himkt** [himkt/pyner#38]
Related to https://github.com/himkt/pyner/pull/37.

I found that when enabling `cuDNN`, it raises `CUDNN_STATUS_BAD_PARAM` in the latest platform.

Currently, I disable cuDNN because it works on GPU if a procedure run without cuDNN. (workaround)
https://github.com/himkt/pyner/pull/37/commits/c168d8eda228d594e0083f1c067a0eb9fda9c03a

```
Exception in main training loop: CUDNN_STATUS_BAD_PARAM
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/usr/local/lib/python3.6/dist-packages/chainer/training/updaters/standard_updater.py", line 175, in update
    self.update_core()
  File "/usr/local/lib/python3.6/dist-packages/chainer/training/updaters/standard_updater.py", line 187, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/usr/local/lib/python3.6/dist-packages/chainer/optimizer.py", line 805, in update
    loss.backward(loss_scale=self._loss_scale)
  File "/usr/local/lib/python3.6/dist-packages/chainer/variable.py", line 1433, in backward
    _backprop_to_all([(node, grad_var)], retain_grad, loss_scale)
  File "/usr/local/lib/python3.6/dist-packages/chainer/variable.py", line 1649, in _backprop_to_all
    func, target_input_indexes, out_grad, in_grad, is_debug)
  File "/usr/local/lib/python3.6/dist-packages/chainer/_backprop_utils.py", line 140, in backprop_step
    _reraise_with_stack(func, e)
  File "/usr/local/lib/python3.6/dist-packages/chainer/_backprop_utils.py", line 138, in backprop_step
    target_input_indexes, grad_outputs)
  File "/usr/local/lib/python3.6/dist-packages/chainer/function.py", line 209, in backward
    gxs = self._function.backward(in_data, grad_out_data)
  File "/usr/local/lib/python3.6/dist-packages/chainer/functions/connection/n_step_rnn.py", line 325, in backward
    dhy, dcy, dys, self.lengths)
  File "cupy/cudnn.pyx", line 1094, in cupy.cudnn.rnn_backward_data
  File "cupy/cuda/cudnn.pyx", line 2186, in cupy.cuda.cudnn.RNNBackwardData
  File "cupy/cuda/cudnn.pyx", line 732, in cupy.cuda.cudnn.check_status
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "train.py", line 173, in <module>
    trainer.run()
  File "/usr/local/lib/python3.6/dist-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/usr/local/lib/python3.6/dist-packages/chainer/training/updaters/standard_updater.py", line 175, in update
    self.update_core()
  File "/usr/local/lib/python3.6/dist-packages/chainer/training/updaters/standard_updater.py", line 187, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/usr/local/lib/python3.6/dist-packages/chainer/optimizer.py", line 805, in update
    loss.backward(loss_scale=self._loss_scale)
  File "/usr/local/lib/python3.6/dist-packages/chainer/variable.py", line 1433, in backward
    _backprop_to_all([(node, grad_var)], retain_grad, loss_scale)
  File "/usr/local/lib/python3.6/dist-packages/chainer/variable.py", line 1649, in _backprop_to_all
    func, target_input_indexes, out_grad, in_grad, is_debug)
  File "/usr/local/lib/python3.6/dist-packages/chainer/_backprop_utils.py", line 140, in backprop_step
    _reraise_with_stack(func, e)
  File "/usr/local/lib/python3.6/dist-packages/chainer/_backprop_utils.py", line 138, in backprop_step
    target_input_indexes, grad_outputs)
  File "/usr/local/lib/python3.6/dist-packages/chainer/function.py", line 209, in backward
    gxs = self._function.backward(in_data, grad_out_data)
  File "/usr/local/lib/python3.6/dist-packages/chainer/functions/connection/n_step_rnn.py", line 325, in backward
    dhy, dcy, dys, self.lengths)
  File "cupy/cudnn.pyx", line 1094, in cupy.cudnn.rnn_backward_data
  File "cupy/cuda/cudnn.pyx", line 2186, in cupy.cuda.cudnn.RNNBackwardData
  File "cupy/cuda/cudnn.pyx", line 732, in cupy.cuda.cudnn.check_status
cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_BAD_PARAM
```

**Comment by himkt** [comment]
https://github.com/himkt/pyner/pull/37#issuecomment-500191511

This patch can investigate input data raising `CUDNN_STATUS_BAD_PARAM`.
(Dataset is CoNLL, created following [README](https://github.com/himkt/pyner/pull/37#issuecomment-500191511))

**Comment by chantera** [comment]
This occurs when `char_inputs` has only one sequence whose length is 1 in `BiLSTM_CRF.char_encode`.
In other words, this happens when processing a sentence that consists of only one character.
CoNLL 2003 `eng.train` has such a sentence `.` in line 278.

Here is a reproduction code.

```py
import chainer
from chainer.backends import cuda
import chainer.functions as F
import numpy as np


class Model(chainer.Chain):

    def __init__(self, n_vocab, n_units, n_tags, impl=0):
        super().__init__()
        with self.init_scope():
            self.embed = chainer.links.EmbedID(n_vocab, n_units)
            self.bilstm = chainer.links.NStepBiLSTM(1, n_units, n_units, 0.5)
            self.linear = chainer.links.Linear(n_units * 2, n_tags)
        self.impl = impl

    def forward(self, xs):
        hy, cy, hs = self.bilstm(None, None, [self.embed(x) for x in xs])
        if self.impl > 0:
            hs = hy.transpose([1, 0, 2]).reshape(len(xs), -1)
            ys = self.linear(hs)
        else:
            d = hs[0].shape[-1] // 2
            features = []
            for h in hs:
                feature = F.concat((h[-1, :d], h[0, d:]), axis=0)
                features.append(feature)
            ys = self.linear(F.vstack(features))
        return ys

    def __str__(self):
        return "{}(impl={})".format(self.__class__.__name__, self.impl)


if __name__ == '__main__':
    chainer.config.use_cudnn = 'always'
    n_vocab = 1000
    n_tags = 128
    n_units = 200

    input0 = (10, 2, 4, 5, 1, 6)
    input1 = (1,)
    model0 = Model(n_vocab, n_units, n_tags, impl=0)
    model1 = Model(n_vocab, n_units, n_tags, impl=1)

    def generate_data(lengths):
        xs = [np.random.randint(n_vocab, size=l) for l in lengths]
        ys = np.random.randint(n_tags, size=len(lengths))
        return xs, ys

    def run(model, lengths):
        print("RUN: model={}, lengths={}".format(model, lengths))
        model.to_gpu()
        model.cleargrads()
        xs, ts = generate_data(lengths)
        ys = model.forward([cuda.to_gpu(x) for x in xs])
        ts = cuda.to_gpu(ts)
        loss = F.softmax_cross_entropy(ys, ts, ignore_label=-1)
        print("loss", loss)
        loss.backward()

    run(model0, input0)
    run(model1, input0)
    run(model0, input1)
    run(model1, input1)  # cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_BAD_PARAM
```

FYI: According to https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#cudnnRNNBackwardData, `CUDNN_STATUS_BAD_PARAM` is returned when
> At least one of the following conditions are met:
> 
> - The descriptor rnnDesc is invalid.
> - At least one of the descriptors dhxDesc, wDesc, hxDesc, cxDesc, dcxDesc, dhyDesc, dcyDesc or one of the descriptors in yDesc, dxdesc, dydesc is invalid.
> - The descriptors in one of yDesc, dxDesc, dyDesc, dhxDesc, wDesc, hxDesc, cxDesc, dcxDesc, dhyDesc, dcyDesc has incorrect strides or dimensions.
> - workSpaceSizeInBytes is too small.
> - reserveSpaceSizeInBytes is too small.

I hope this will help you fix.

**Comment by himkt** [comment]
Actually, I encountered the problem before, and it solved with [the workaround](https://github.com/himkt/pyner/blob/master/pyner/named_entity/recognizer.py#L173) at that time.
In the case, the error occurred because a shape of ndarray whose length is 1 was not `(1, 1)` but `(1,)` . (It may be related to this problem... 🤔 )

I forgot this workaround and I will investigate it. 
Thanks, @chantera  very much for providing relevant information!

**Comment by himkt** [comment]
It found that this problem is caused by CuPy.
ref: https://github.com/cupy/cupy/pull/2261

**Comment by himkt** [comment]
Solved in https://github.com/himkt/pyner/pull/41
